// Generated by https://quicktype.io

export interface AllActionables {
    message: Actionables[];
}

export interface Actionables {
    id:            string;
    task:          string;
    dueDate:       string;
    completedDate: null;
    owner:         Owner;
}

export interface Owner {
    id:       string;
    name:     string;
    lastName: string;
}
