// Generated by https://quicktype.io

export interface AllFollowUPS {
    message: FollowUps[];
}

export interface FollowUps {
    id:          string;
    temperature: number;
    fu_date:     string;
    meeting_id:  MeetingID;
}

export interface MeetingID {
    id:     string;
    date:   string;
    topics: string;
    title:  string;
}
