// Generated by https://quicktype.io

export interface AllMeetings {
    message: Meetings[];
}

export interface Meetings {
    id:       string;
    date:     string;
    topics:   null;
    title:    string;
    owner:    Attendee;
    attendee: Attendee;
}

export interface Attendee {
    id:       string;
    name:     string;
    lastName: string;
}
