// Generated by https://quicktype.io

export interface AllUsers {
    message: Users[];
}

export interface Users {
    id:              string;
    name:            string;
    lastName:        string;
    ownerMetting:    Metting[];
    attendeeMetting: Metting[];
    actionables:     Actionable[];
}

export interface Actionable {
    id:            string;
    task:          string;
    dueDate:       string;
    completedDate: null;
}

export interface Metting {
    id:     string;
    date:   string;
    topics: string;
    title:  string;
}
