"message": {
    "id": "a0d93925-89a6-4157-8a41-26fd5e2358a8",
    "name": "Oscar",
    "lastName": "Eberle",
    "ownerMetting": [
        {
            "id": "3f95b54b-0813-44c2-9583-10b8cb8f2e61",
            "date": "2023-09-13T13:38:06.000Z",
            "topics": "hacer 1 cosa",
            "title": "Primer One on One"
        },
        {
            "id": "67c1f604-fb66-401f-8401-d499553fd50c",
            "date": "2023-09-13T13:40:37.000Z",
            "topics": null,
            "title": "Primer One on One"
        }
    ],
    "attendeeMetting": [
        {
            "id": "574b316d-ba13-4d01-bd3e-8ae0d47d369c",
            "date": "2023-09-13T13:41:01.000Z",
            "topics": null,
            "title": "Primer One on One"
        }
    ],
    "actionables": [
        {
            "id": "ddc3ad23-1818-445d-b774-e3d3eb0aff91",
            "task": "Chequear Subalternos y reportarlo",
            "dueDate": "2023-05-23T00:00:00.000Z",
            "completedDate": null
        }
    ]
}