// Generated by https://quicktype.io

export interface FindAllDTO {
    skip: string;
    take: string;
}


/* 
{
        "id": "55a839c2-83ad-4970-a281-1530b402c357",
        "name": "kevin",
        "lastName": "aviles",
        "ownerMetting": [],
        "attendeeMetting": [],
        "actionables": []
    }

    {
        "id": "3e02b602-3f78-4f6f-ac83-1311813224cc",
        "name": "OscarRR",
        "lastName": "Eberle",
        "ownerMetting": [],
        "attendeeMetting": [
            {
                "id": "22e52d54-2f33-4bda-91bd-5daa62042e55",
                "date": "2023-08-09T20:23:29.000Z",
                "topics": "resolverasdasd esto",
                "title": "Primera meeting"
            }
        ],
        "actionables": []
    }
*/