// Generated by https://quicktype.io
/* 
export interface UpdateUserDTO {
    id:              string;
    name:            string;
    lastName:        string;
    ownerMetting:    OwnerMetting[];
    attendeeMetting: any[];
    actionables:     Actionable[];
}

export interface Actionable {
    id:            string;
    task:          string;
    dueDate:       null;
    completedDate: null;
}

export interface OwnerMetting {
    id:     string;
    date:   string;
    topics: string;
    title:  string;
}
 */
//SABER COMO QUITAR DESPUES EL UNDEFINED
export interface UpdateUserDTO {
    id?:              string; 
    name?:            string;
    lastName?:        string;
    ownerMetting?:    any[];
    attendeeMetting?: any[];
    actionables?:     any[];
}
